export const products = [
  {
    slug: "fl15",
    name: "FL15",
    tagline: "Performance Stadium Floodlight",
    image: "light-1",
    description:
      "A performance-oriented floodlight designed for higher poles and broader pitch coverage. Built for projects demanding superior uniformity and tighter beam control.",
    power: ["400W", "500W", "800W", "1000W", "1200W", "1500W", "1600W", "2000W"],
    efficiency: "140–150 lm/W",
    lumens: "58,000 – 225,000 lm",
    cri: ["70", "80 Optional", "90 Optional"],
    cct: "3000K–6500K",
    ip: "IP66 · IK08 / IK10",
    controls: ["DALI", "DALI-2", "DMX512", "0-10V"],
    beam: ["15°", "30°", "45°", "60°", "90°", "120°", "P45"],
    features: [
      "Long throw optics",
      "Glare control",
      "Spill light management",
      "Surge protection",
      "Flicker-free drivers",
      "Die cast aluminum construction",
      "Tool-free module replacement",
      "Precision aiming bracket",
    ],
    applications: ["Professional stadiums", "Football grounds", "Cricket stadiums", "Sports arenas"],
  },
  {
    slug: "fl12",
    name: "FL12",
    tagline: "Glare-Control Sports Floodlight",
    image: "light-4",
    description:
      "Designed for venues requiring strict glare reduction and neighborhood spill light control.",
    power: ["600W", "800W", "1000W", "1200W", "1500W"],
    efficiency: "125–155 lm/W",
    lumens: "81,000 – 187,500 lm",
    cri: ["70", "80", "90+", "TLCI90+"],
    cct: "3000K–6500K",
    ip: "IP66 · IK08",
    controls: ["DALI", "DALI-2", "DMX512", "0-10V"],
    beam: ["10°", "20°", "45°", "FT6"],
    features: [
      "Glare control",
      "Spill light management",
      "Flexible aiming",
      "Precision optics",
      "Outdoor durability",
    ],
    applications: ["Professional sports venues", "Broadcast stadiums", "Residential-adjacent facilities"],
  },
  {
    slug: "fl10",
    name: "FL10",
    tagline: "Versatile Stadium Floodlight",
    image: "light-3",
    description: "Versatile floodlight covering diverse sports lighting layouts.",
    power: ["500W", "600W", "800W", "1000W", "1200W", "1600W", "2000W"],
    efficiency: "125–180 lm/W",
    lumens: "90,000 – 250,000 lm",
    cri: ["70", "80", "90"],
    cct: "3000K–6500K",
    ip: "IP66 · IK10",
    controls: ["DALI 2.0", "DMX512", "0-10V"],
    beam: ["10°", "15°", "20°", "30°", "60°"],
    features: [
      "Laser aiming system",
      "Efficient heat sink",
      "Weather resistance",
      "Spill light control",
      "Glare reduction",
    ],
    applications: ["Training grounds", "Regional stadiums", "Multi-sport complexes"],
  },
  {
    slug: "fl08",
    name: "FL08",
    tagline: "High-Value Stadium Floodlight",
    image: "light-2",
    description: "Budget-conscious stadium lighting solution balancing performance and cost.",
    power: ["200W", "250W", "400W", "500W", "600W", "750W", "800W", "1000W"],
    efficiency: "160–165 lm/W",
    lumens: "33,000 – 160,000 lm",
    cri: ["70", "80", "90", "TLCI90"],
    cct: "3000K–6500K",
    ip: "IP66 · IK08",
    controls: ["DALI", "0-10V"],
    beam: ["25°", "45°", "60°", "90°", "80×145", "80×152", "120×148", "45×105"],
    features: ["RGBW Available", "Compact module", "High efficacy"],
    applications: ["Community stadiums", "Training facilities", "Outdoor sports grounds"],
  },
  {
    slug: "pl08",
    name: "PL08",
    tagline: "Tennis Court Lighting Luminaire",
    image: "light-6",
    description:
      "Developed specifically around tennis court layouts and strict glare requirements.",
    power: ["240W", "320W", "400W", "500W"],
    efficiency: "150–165 lm/W",
    lumens: "39,600 – 75,000 lm",
    cri: ["70", "80", "90"],
    cct: "3000K–6500K",
    ip: "IP66 · IK08",
    controls: ["DALI", "0-10V"],
    beam: ["25°", "45°", "60°", "90°", "80×152", "80×145", "120×148", "P60"],
    features: [
      "Strong glare control",
      "No spill light options",
      "Court optimized optics",
      "Uniform lighting",
    ],
    applications: ["Tennis courts", "Padel courts", "Training courts"],
  },
  {
    slug: "fl07",
    name: "FL07",
    tagline: "Ultra High Power Modular Stadium Floodlight",
    image: "light-2",
    description: "Flagship modular floodlight for large-scale stadiums.",
    power: ["400W – 3200W"],
    efficiency: "165–185 lm/W",
    lumens: "74,000 – 528,000 lm",
    cri: ["70", "80", "90"],
    cct: "3000K–6500K",
    ip: "IP66 · IK08 / IK10",
    controls: ["DALI-2", "DMX512", "0-10V"],
    beam: ["30°", "45°", "60°"],
    features: [
      "Independent module operation",
      "No downtime maintenance",
      "Modular scalability",
      "Long throw optics",
      "Heavy duty construction",
    ],
    applications: ["International stadiums", "Mega sports venues", "Large event infrastructure"],
  },
] as const;

export const solar = [
  {
    slug: "juno-street",
    name: "JUNO LED Solar Street Light",
    image: "light-5",
    description: "Smart, self-sustaining street lighting engineered for highways and urban grids.",
    specs: {
      Heights: "6m · 8m · 10m · 12m",
      Power: "20W · 30W · 20W×2 · 30W×2",
      "Solar Panel": "200W / 400W HPBC",
      Battery: "LiFePO4 40Ah / 50Ah",
      Efficiency: "110–150 lm/W",
      Protection: "IP65 · IK08",
    },
    features: ["CREE / OSRAM / Nichia / Lumileds LEDs", "Smart dimming", "3000-cycle battery", "Bird spike protection"],
    applications: ["Roads", "Highways", "Urban infrastructure"],
  },
  {
    slug: "juno-area-a",
    name: "JUNO Solar Area Light A",
    image: "light-5",
    description: "Architectural area illumination for commercial and civic spaces.",
    specs: {
      Heights: "4m · 6m · 8m",
      Power: "20W · 20W×2",
      Efficiency: "150–170 lm/W",
      Battery: "LiFePO4",
      Solar: "200W HPBC",
    },
    features: ["High efficacy optics", "Slim aluminium body", "Autonomous control"],
    applications: ["Commercial areas", "Business parks", "Public spaces"],
  },
  {
    slug: "juno-area-b",
    name: "JUNO Solar Area Light B",
    image: "light-5",
    description: "Urban-scale solar luminaire for streets and landscape applications.",
    specs: {
      Heights: "6m · 8m · 10m",
      Power: "20W · 20W×2",
      Efficiency: "150–170 lm/W",
    },
    features: ["Tunable distribution", "Maintenance-free", "Smart sensor ready"],
    applications: ["Urban streets", "Landscape", "Commercial developments"],
  },
  {
    slug: "juno-post-top",
    name: "JUNO Solar Post Top",
    image: "light-5",
    description: "Sculpted post-top luminaire for pedestrian environments.",
    specs: { Height: "4m", Power: "20W", Efficiency: "150–170 lm/W" },
    features: ["360° distribution", "Integrated battery", "Anti-vandal"],
    applications: ["Parks", "Walkways", "Residential communities"],
  },
  {
    slug: "juno-bollard",
    name: "JUNO Solar Bollard",
    image: "light-5",
    description: "Precision bollard light for landscape paths and luxury gardens.",
    specs: {
      Models: "ST-Jupiter-C1 · C2 · C3",
      Height: "1140mm",
      Power: "1.5W",
      Efficiency: "150–170 lm/W",
    },
    features: ["Marine-grade body", "Soft downward glow", "Zero-cable install"],
    applications: ["Landscape paths", "Luxury gardens", "Hospitality projects"],
  },
] as const;

import l1 from "./light-1.png.asset.json";
import l2 from "./light-2.png.asset.json";
import l3 from "./light-3.png.asset.json";
import l4 from "./light-4.png.asset.json";
import l5 from "./light-5.png.asset.json";
import l6 from "./light-6.png.asset.json";

export const imageUrls: Record<string, string> = {
  "light-1": l1.url,
  "light-2": l2.url,
  "light-3": l3.url,
  "light-4": l4.url,
  "light-5": l5.url,
  "light-6": l6.url,
};
